# Nombre del flujo de trabajo que aparecerá en la pestaña "Actions" de GitHub
name: Deploy ASP.NET Core App to Oracle VPS (Clinic)

# Disparador: Este flujo se ejecuta cada vez que se hace un push a la rama 'master'
on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:

  # El tipo de máquina virtual donde se ejecutará el trabajo
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout: Descarga tu código del repositorio a la máquina virtual de GitHub
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Setup .NET: Instala el SDK de .NET Core en la máquina virtual
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        # Asegúrate de que esta versión coincida con la de tu proyecto
        dotnet-version: '9.0.300'
    
    # 3. Publish: Crea los archivos listos para producción
    - name: Publish
      run: dotnet publish Clinic --self-contained true --output /home/runner/work/dotnet-webapp --runtime linux-arm64

    # 4. Copy files: Copiar archivos usando SCP
    - name: Copy files via SSH
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "/home/runner/work/dotnet-webapp"
        target: ${{ secrets.TARGET_DIR }}
        strip_components: 4
        rm: true
      
    # 5. Update files on remote: Copiar archivos usando SSH
    - name: Execute remote SSH commands using key
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: sudo rm ${{ secrets.PUBLISH_DIR }}/* -rf && sudo cp ${{ secrets.TARGET_DIR }}/* ${{ secrets.PUBLISH_DIR }} -R && sudo chmod +x ${{ secrets.PUBLISH_DIR }}/Clinic && sudo chown dotnet-user:dotnet ${{ secrets.PUBLISH_DIR }} -R  && sudo systemctl restart clinic.service
